//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerPeripheralsShop.Database
{
    using System;
    using System.Collections.Generic;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_List = new HashSet<Order_List>();
        }

        public Order(int user_Id, int order_id, DateTime order_Date, decimal total_Price, int items_Number)
        {
            this.User_Id = user_Id;
            this.Order_Id = order_id;
            this.Order_Date = order_Date;
            this.Total_Price = total_Price;
            this.Items_Number = items_Number;
        }

        public int Order_Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Order_Date { get; set; }
        public decimal Total_Price { get; set; }
        public int Items_Number { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_List> Order_List { get; set; }
        public virtual User User { get; set; }
    }
}