//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerPeripheralsShop.Database
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Order_List
    {
        public Order_List(int product_id, int order_id, int order_list_id)
        {
            this.Product_Id = product_id;
            this.Order_Id = order_id;
            this.Order_List_Id = order_list_id;
        }
        public int Product_Id { get; set; }
        public int Order_Id { get; set; }
        public int Order_List_Id { get; set; }

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }

        public string ProductModel
        {
            get
            {
                using (ComputerPeripheralsShopEntities context = new ComputerPeripheralsShopEntities())
                {
                    return (from product in context.Product
                            where product.Product_Id.Equals(Product_Id)
                            select product.Manufacturer).Single<string>() + " " +
                            (from product in context.Product
                             where product.Product_Id.Equals(Product_Id)
                             select product.Model).Single<string>();
                }
            }
        }
    }
}
