//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerPeripheralsShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_List = new HashSet<Order_List>();
        }
    
        public int Product_Id { get; set; }
        public string Category { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string Connection_Type { get; set; }
        public string Weight { get; set; }
        public bool Backlight { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public Nullable<int> dpi { get; set; }
        public Nullable<bool> Microphone { get; set; }
        public bool Gaming_mode { get; set; }
        public decimal Price { get; set; }
        public int Number_on_warehouse { get; set; }
        public byte[] Picture_Main { get; set; }
        public byte[] Picture1 { get; set; }
        public byte[] Picture2 { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public byte[] MenuPicture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_List> Order_List { get; set; }
    }
}
